# Generated by Django 5.0.6 on 2024-06-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enjoy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
