# Generated by Django 5.0.6 on 2024-07-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enjoy', '0003_alter_post_conteudo_alter_post_resumo_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='conteudo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='resumo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
